/**
 * AC ADEXA - Image Sharing & Web Share Generator
 * Renders professional social-media ready academic result cards on Canvas.
 */

class ResultSharer {
  /**
   * Generate result card image on canvas
   * @param {object} params - { sgpa, cgpa, semester, regulation, studentName, showName, showRegulation }
   */
  static generateResultCanvas(params) {
    const canvas = document.createElement('canvas');
    canvas.width = 600;
    canvas.height = 400;
    const ctx = canvas.getContext('2d');

    // Background Gradient (Dark Navy / Academic Teal accent)
    const bgGrad = ctx.createLinearGradient(0, 0, 600, 400);
    bgGrad.addColorStop(0, '#0F172A');
    bgGrad.addColorStop(1, '#1E293B');
    ctx.fillStyle = bgGrad;
    ctx.fillRect(0, 0, 600, 400);

    // Accent Card Top Border
    const accentGrad = ctx.createLinearGradient(0, 0, 600, 0);
    accentGrad.addColorStop(0, '#2563EB');
    accentGrad.addColorStop(0.5, '#0D9488');
    accentGrad.addColorStop(1, '#6EE7B7');
    ctx.fillStyle = accentGrad;
    ctx.fillRect(0, 0, 600, 8);

    // Header - AC ADEXA Brand
    ctx.fillStyle = '#FFFFFF';
    ctx.font = '900 28px sans-serif';
    ctx.fillText('AC ADEXA', 40, 55);

    ctx.fillStyle = '#0D9488';
    ctx.font = '600 12px sans-serif';
    ctx.fillText('YOUR ACADEMIC COMPANION', 40, 75);

    // Student Name & Metadata (if enabled)
    if (params.showName && params.studentName) {
      ctx.fillStyle = '#94A3B8';
      ctx.font = '600 14px sans-serif';
      ctx.fillText(`Student: ${params.studentName.toUpperCase()}`, 40, 110);
    }

    if (params.showRegulation) {
      ctx.fillStyle = '#38BDF8';
      ctx.font = '700 13px sans-serif';
      ctx.textAlign = 'right';
      ctx.fillText(`${params.regulation || 'R25'}`, 560, 55);
      if (params.semester) {
        ctx.fillStyle = '#94A3B8';
        ctx.fillText(`Semester ${params.semester}`, 560, 75);
      }
      ctx.textAlign = 'left';
    }

    // Divider
    ctx.strokeStyle = '#334155';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(40, 125);
    ctx.lineTo(560, 125);
    ctx.stroke();

    // Result Metric Box (SGPA)
    ctx.fillStyle = '#1E3A8A';
    ctx.beginPath();
    ctx.roundRect(40, 155, 250, 140, 16);
    ctx.fill();

    ctx.fillStyle = '#93C5FD';
    ctx.font = '700 13px sans-serif';
    ctx.fillText('SEMESTER SGPA', 60, 185);

    ctx.fillStyle = '#FFFFFF';
    ctx.font = '900 52px sans-serif';
    ctx.fillText(params.sgpa ? Number(params.sgpa).toFixed(2) : 'N/A', 60, 255);

    // Result Metric Box (CGPA)
    if (params.cgpa) {
      ctx.fillStyle = '#115E59';
      ctx.beginPath();
      ctx.roundRect(310, 155, 250, 140, 16);
      ctx.fill();

      ctx.fillStyle = '#99F6E4';
      ctx.font = '700 13px sans-serif';
      ctx.fillText('CUMULATIVE CGPA', 330, 185);

      ctx.fillStyle = '#FFFFFF';
      ctx.font = '900 52px sans-serif';
      ctx.fillText(Number(params.cgpa).toFixed(2), 330, 255);
    }

    // Footer - Tagline
    ctx.fillStyle = '#64748B';
    ctx.font = '600 13px sans-serif';
    ctx.fillText('Calculate • Plan • Track • Improve', 40, 345);

    ctx.fillStyle = '#475569';
    ctx.font = '500 11px sans-serif';
    ctx.textAlign = 'right';
    ctx.fillText(`Generated by AC ADEXA on ${new Date().toLocaleDateString()}`, 560, 345);

    return canvas;
  }

  static downloadResultImage(params) {
    const canvas = this.generateResultCanvas(params);
    const link = document.createElement('a');
    link.download = `ac-adexa-result-sem${params.semester || 1}.png`;
    link.href = canvas.toDataURL('image/png');
    link.click();
  }

  static async shareResultImage(params) {
    const canvas = this.generateResultCanvas(params);
    canvas.toBlob(async (blob) => {
      if (!blob) return;
      const file = new File([blob], 'ac-adexa-result.png', { type: 'image/png' });

      if (navigator.canShare && navigator.canShare({ files: [file] })) {
        try {
          await navigator.share({
            title: 'AC ADEXA Academic Result',
            text: `Check out my academic performance calculated with AC ADEXA!`,
            files: [file]
          });
          return;
        } catch (e) {
          console.warn('Web Share cancelled or failed', e);
        }
      }

      // Fallback: Download image
      this.downloadResultImage(params);
    });
  }
}
