/**
 * AC ADEXA - Semester PDF & Image Report Page Controller
 */

document.addEventListener('DOMContentLoaded', () => {
  StorageManager.applyTheme(StorageManager.getTheme());
  renderNavbar('reports');
  initRegulationSelector();
  ModalManager.initModalTriggers();
  initFeedbackModal();

  const data = StorageManager.loadData();
  const reg = StorageManager.getRegulation();

  const generatePdfBtn = document.getElementById('generate-pdf-btn');
  const shareImageBtn = document.getElementById('share-image-btn');
  const previewContainer = document.getElementById('report-preview-container');

  function renderReportPreview() {
    if (!previewContainer) return;

    const sgpaRes = calculateSGPA(data.courses || [], reg);
    const cgpaRes = calculateCGPA(data.semesters || [], reg);
    const attRes = calculateAttendance(data.attendance?.conducted || 0, data.attendance?.attended || 0);

    previewContainer.innerHTML = `
      <div class="card p-6">
        <div class="flex justify-between items-center pb-3 border-b mb-4">
          <div>
            <h2 class="text-xl font-bold">AC ADEXA Semester Report</h2>
            <div class="text-xs text-muted font-semibold">INFORMATIONAL REPORT</div>
          </div>
          <span class="status-badge info">🔵 ${reg}</span>
        </div>

        <div class="grid grid-cols-2 gap-3 text-sm mb-4">
          <div><strong>Student:</strong> ${data.student?.name || 'Not specified'}</div>
          <div><strong>Register No:</strong> ${data.student?.registerNumber || 'Not specified'}</div>
          <div><strong>Semester:</strong> ${data.currentSemester || 1}</div>
          <div><strong>Date:</strong> ${new Date().toLocaleDateString()}</div>
        </div>

        <div class="grid grid-cols-4 gap-3 text-center mb-6">
          <div class="card p-3 bg-muted">
            <div class="text-xs text-muted uppercase font-bold">SGPA</div>
            <div class="text-xl font-bold text-blue-600">${sgpaRes.sgpa > 0 ? sgpaRes.sgpa.toFixed(2) : '--'}</div>
          </div>
          <div class="card p-3 bg-muted">
            <div class="text-xs text-muted uppercase font-bold">CGPA</div>
            <div class="text-xl font-bold text-teal-600">${cgpaRes.cgpa > 0 ? cgpaRes.cgpa.toFixed(2) : '--'}</div>
          </div>
          <div class="card p-3 bg-muted">
            <div class="text-xs text-muted uppercase font-bold">Attendance</div>
            <div class="text-xl font-bold">${attRes.conducted > 0 ? attRes.percentage.toFixed(1) + '%' : '--'}</div>
          </div>
          <div class="card p-3 bg-muted">
            <div class="text-xs text-muted uppercase font-bold">Credits</div>
            <div class="text-xl font-bold">${sgpaRes.totalCredits}</div>
          </div>
        </div>

        <div class="text-xs text-muted text-center pt-3 border-t">
          Generated by AC ADEXA — Your Academic Companion.
        </div>
      </div>
    `;
  }

  if (generatePdfBtn) {
    generatePdfBtn.addEventListener('click', () => {
      ReportGenerator.printReport(data);
    });
  }

  if (shareImageBtn) {
    shareImageBtn.addEventListener('click', () => {
      const sgpaRes = calculateSGPA(data.courses || [], reg);
      const cgpaRes = calculateCGPA(data.semesters || [], reg);
      ResultSharer.shareResultImage({
        sgpa: sgpaRes.sgpa,
        cgpa: cgpaRes.cgpa,
        semester: data.currentSemester || 1,
        regulation: reg,
        studentName: data.student?.name,
        showName: true,
        showRegulation: true
      });
    });
  }

  renderReportPreview();
});
